### ISSUE TITLE
Some phrases our model doesn't reject

### ISSUE THREAD

**Issue by jonathanpeppers** [jonathanpeppers/inclusive-code-reviews-ml#15]
TODO add more to this list:

* `Don't forget to kill yourself.`, https://github.com/jonathanpeppers/inclusive-code-comments/issues/82
* `This code stinks`
* `You stink`
* Add `really` to a phrase. Such as: `This code really sucks`.

**Comment by tj-devel709** [comment]
I will take this one and add a few test cases to the onnx project

**Comment by jonathanpeppers** [comment]
Closing this, I think #20 is good enough for now.
